# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
  actions: write # ✅ 添加这个，确保 deploy-pages 能正确访问 Actions

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Node.js 版本
        uses: pnpm/action-setup@v4.1.0
        with:
          # Version of pnpm to install
          version: 10.4.1 # optional
          # Where to store pnpm files
          #dest: # optional, default is ~/setup-pnpm
          # If specified, run `pnpm install`
          #run_install: # optional, default is null
          # File path to the package.json to read "packageManager" configuration
          #package_json_file: # optional, default is package.json
          # When set to true, @pnpm/exe, which is a Node.js bundled package, will be installed, enabling using pnpm without Node.js.
          #standalone: # optional, default is false

      - name: 安装依赖
        run: pnpm install

      - name: build项目
        run: pnpm run build:prod

      - name: 检查 dist 目录是否存在
        run: ls -l dist # 确保 dist 目录存在

      # 部署到 GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # 将构建结果发布到 gh-pages 分支
          folder: dist # Vite 默认构建目录为 build，可以根据你的配置修改
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub 提供的自动生成 token，用于认证操作
